[workspace]
channels = [
  "https://prefix.dev/pixi-build-backends",
  "conda-forge",
  # "https://prefix.dev/conda-forge",
  "conda-forge/label/ty_alpha",
]
platforms = ["win-64", "linux-64", "osx-arm64"]
preview = ["pixi-build"]
license = "MIT"
license-file = "LICENSE"
requires-pixi = ">=0.53.0"


[tasks]

[dependencies]
sillywalk = { path = "." }

[package]
name = "sillywalk"
version = "1.0.0"

[package.build]
backend = { name = "pixi-build-python", version = ">=0.3.2" }

[package.host-dependencies]
uv-build = "*"
uv = "*"

[package.run-dependencies]
numpy = "*"
scikit-learn = "*"
narwhals = "*"
jinja2 = "*"

[feature.test.dependencies]
pytest = ">=6"
pytest-cov = "*"
marimo = "*"
uv = "*"
nodejs = "*"
polars = "*"
pandas = "*"
pyarrow = "*"
pandas-stubs = "*"
debugpy = "*"
altair = "*"
ruff = "*"

[feature.test.tasks]
test = "pytest"
test-coverage = "pytest --cov=sillywalk --cov-report=xml --cov-report=term-missing"
marimo-test = "marimo edit tests/test_notebook.py"

[feature.build.dependencies]
python-build = "*"
twine = "*"
wheel = "*"
uv-build = "*"

[feature.build.tasks]
build-wheel = "python -m build --no-isolation ."
check-wheel = "twine check dist/*"


[feature.lint.dependencies]
pre-commit = "*"
insert-license-header = "*"
docformatter = "*"
ruff = "*"
prettier = "*"
taplo = "*"
pre-commit-hooks = "*"
typos = "*"
ty = "*"

[feature.lint.tasks]
pre-commit-install = "pre-commit install"
lint = "pre-commit run -a"
typecheck-python = "ty check"

[feature.py311.dependencies]
python = "3.11.*"
[feature.py312.dependencies]
python = "3.12.*"
[feature.py313.dependencies]
python = "3.13.*"
[feature.py314.dependencies]
python = "3.14.*"

[environments]
default = ["py314", "test"]
py311 = ["py311", "test"]
py312 = ["py312", "test"]
py313 = ["py313", "test"]
py314 = ["py314", "test"]
build = ["build"]
lint = { features = ["lint"], no-default-feature = true }
